theme: minima
header_pages:
  - documentation/README.md
  - deploys/README.md
  - SECURITY.md
plugins:
  - jemoji
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
github_username:  ETERNA-earkiv
title: ETERNA
description: ETERNA is a long-term digital repository solution that delivers functionalities for all the main functional units of the OAIS reference model. ETERNA is capable of ingesting, managing, and providing access to various types of digital content produced by large corporations and public bodies.
author: WhiteRed
logo: https://keeps.github.io/roda/roda-ui/roda-wui/src/main/resources/config/theme/favicon/favicon-black-196.png
