services:
  zoo:
    image: ghcr.io/eterna-earkiv/zookeeper:3.9.5
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      - ZOO_4LW_COMMANDS_WHITELIST=mntr,conf,ruok
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog

  solr:
    image: ghcr.io/eterna-earkiv/solr:9.10.1
    user: "8983"
    restart: unless-stopped
    ports:
      - "8983:8983"
    environment:
      SOLR_HEAP: 2g
      ZK_HOST: zoo:2181
      SOLR_HOST: localhost
      SOLR_OPTS: "-Dsolr.environment=dev,label=DEV+ENV"
    depends_on:
      - zoo
    command:
      - -c
    volumes:
      - solr_data:/var/solr

  clamd:
    image: docker.io/clamav/clamav:stable
    restart: unless-stopped
    ports:
      - "3310:3310"
    volumes:
      - clam_data:/var/lib/clamav
      # Mapping $HOME/.roda to enable usage with spring-boot mode
      - ${HOME}/.roda/data/storage:${HOME}/.roda/data/storage:ro
      - ${HOME}/.roda/data/staging-storage:${HOME}/.roda/data/staging-storage:ro
      # Mapping /tmp to enable usage with local testing via mvn test
      - /tmp:/tmp

  siegfried:
    image: ghcr.io/eterna-earkiv/siegfried:v1.11.4
    restart: unless-stopped
    ports:
      - "5138:5138"
    environment:
      SIEGFRIED_HOST: 0.0.0.0
      SIEGFRIED_PORT: 5138
    volumes:
      - siegfried_data:/root/siegfried/
      # Mapping $HOME/.roda to enable usage with spring-boot mode
      - ${HOME}/.roda/data/storage:${HOME}/.roda/data/storage:ro
      - ${HOME}/.roda/data/staging-storage:${HOME}/.roda/data/staging-storage:ro
      # Mapping /tmp to enable usage with local testing via mvn test
      - /tmp:/tmp:ro

  swagger:
    image: docker.io/swaggerapi/swagger-ui:latest
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      - URL=http://localhost:8080/api/openapi.json
      - DOC_EXPANSION=none
      - VALIDATOR_URL=none

  mailpit:
    image: axllent/mailpit:v1.29.2
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui

  openldap:
    image: vegardit/openldap:latest
    container_name: openldap
    restart: unless-stopped
    ports:
      - "1389:389"
      - "1636:636"
    environment:
      - LDAP_INIT_ORG_DN=DC=roda,DC=org
      - LDAP_INIT_ORG_NAME=RODA
      - LDAP_INIT_ROOT_USER_DN=cn=admin,dc=roda,dc=org
      - LDAP_INIT_ROOT_USER_PW=eterna
      - LDAP_TLS_ENABLED=false
    volumes:
      - ./ldap/ldifs/init_org_tree.ldif:/opt/ldifs/init_org_tree.ldif:ro
      - ./ldap/ldifs/init_org_entries.ldif:/opt/ldifs/init_org_entries.ldif:ro
      - ./ldap/ldifs/init_org_ppolicy.ldif:/opt/ldifs/init_org_ppolicy.ldif:ro

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: roda
      POSTGRES_DB: roda_core_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  zookeeper_data:
  zookeeper_datalog:
  solr_data:
  clam_data:
  siegfried_data:
  pg_data:
