#!/bin/bash

# Configure clamdscan to connect to clamd via TCP if env vars are set.
# By default clamdscan looks for a local socket; in Docker, clamd runs in a
# separate container and must be reached over TCP.
if [ -n "$CLAMD_TCPADDR" ] && [ -n "$CLAMD_TCPSOCKET" ]; then
    if ! cat > /etc/clamd.conf <<EOF
# Generated by docker-entrypoint.d/00-start_dependencies.sh
TCPAddr $CLAMD_TCPADDR
TCPSocket $CLAMD_TCPSOCKET
EOF
    then
        echo "Failed to write /etc/clamd.conf" >&2
        exit 1
    fi
    echo "Configured clamdscan to use TCP $CLAMD_TCPADDR:$CLAMD_TCPSOCKET"
fi
