services:
  zoo:
    image: ghcr.io/eterna-earkiv/zookeeper:3.9.5
    restart: unless-stopped
    ports:
      - "2182:2181"
    environment:
      - ZOO_4LW_COMMANDS_WHITELIST=mntr,conf,ruok
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog

  solr:
    image: ghcr.io/eterna-earkiv/solr:9.10.1
    restart: unless-stopped
    ports:
      - "8984:8984"
    environment:
      ZK_HOST: zoo:2181
      SOLR_HOST: localhost
      SOLR_PORT: "8984"
    depends_on:
      - zoo
    command:
      - -c
    volumes:
      - solr_data:/var/solr

  clamd:
    image: docker.io/clamav/clamav:stable
    restart: unless-stopped
    ports:
      - "3311:3310"
    volumes:
      - clam_data:/var/lib/clamav
      - $HOME/.roda_central/data/storage:$HOME/.roda_central/data/storage

  siegfried:
    image: ghcr.io/eterna-earkiv/siegfried:v1.11.4
    restart: unless-stopped
    ports:
      - "5139:5138"
    environment:
      SIEGFRIED_HOST: siegfried
      SIEGFRIED_PORT: 5138
    volumes:
      - siegfried_data:/root/siegfried/
      - $HOME/.roda_central/data/storage:$HOME/.roda_central/data/storage

  swagger:
    image: docker.io/swaggerapi/swagger-ui:latest
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      - URL=http://localhost:8080/api/openapi.json
      - DOC_EXPANSION=none
      - VALIDATOR_URL=none

  mailpit:
    image: axllent/mailpit:v1.24
    restart: unless-stopped
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui

  openldap:
    image: docker.io/bitnamilegacy/openldap:2.6
    user: 1001:root
    ports:
      - "1388:1389"
      - "1637:1636"
    environment:
      - BITNAMI_DEBUG=true
      - LDAP_ROOT=dc=roda,dc=org
      - LDAP_SKIP_DEFAULT_TREE=yes
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=roda
      - LDAP_EXTRA_SCHEMAS=cosine,inetorgperson,nis,pbkdf2
    volumes:
      - ldap_data:/opt/bitnami/openldap/etc/schema/pbkdf2.ldif

  unoserver:
    image: ghcr.io/eterna-earkiv/eterna-unoserver:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 2003 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s



volumes:
  zookeeper_data:
  zookeeper_datalog:
  solr_data:
  clam_data:
  siegfried_data:
  ldap_data: